import assert from 'node:assert/strict';
import { exportDocx } from '../../../public/features/documents/docx-export.js';
import { richContent, PNG } from '../../support/rich-fixture.js';

export async function verifyDocx({ page, cdp, base, screenshot }) {
  const owner = await page();
  const saved = "JSON.parse(localStorage.getItem('docdoc.documents.v1'))";
  const editor = "document.querySelector('#rich-editor .tiptap').editor";
  assert.equal(await owner.evaluate(`${saved}[0].kind`), 'markdown');
  await owner.evaluate("document.querySelector('#new').click()");
  assert.equal(await owner.evaluate("document.querySelector('#new-kind').value"), 'markdown');
  await screenshot(owner, 'document-choice');
  await owner.evaluate("document.querySelector('#new-kind').value='docx'; document.querySelector('#new-create').click(); document.querySelector('#title').value='Rich team report'; document.querySelector('#title').dispatchEvent(new Event('input'))");
  await owner.wait("!!document.querySelector('#rich-editor .tiptap')");
  assert.equal(await owner.evaluate(`${saved}.find(r=>r.state.title.value==='Rich team report').kind`), 'docx');
  assert.equal(await owner.evaluate("getComputedStyle(document.querySelector('#vim-toggle')).display"), 'none');
  const fixture = await exportDocx(richContent, 'Fixture', async src => ({ src, width: 1, height: 1 }));
  const encoded = Buffer.from(await fixture.arrayBuffer()).toString('base64');
  await owner.evaluate(`(async () => {
    const bytes=Uint8Array.from(atob(${JSON.stringify(encoded)}), c=>c.charCodeAt(0));
    Object.defineProperty(document.querySelector('#docx-input'), 'files', {value:[new File([bytes],'fixture.docx')],configurable:true});
    await document.querySelector('#docx-input').onchange();
  })()`);
  assert.match(await owner.evaluate("document.querySelector('#notice').textContent"), /Imported DOCX/);
  const content = await owner.evaluate(`${editor}.getJSON()`), html = await owner.evaluate(`${editor}.getHTML()`);
  for (const pattern of [/<h2>/, /<strong>Bold<\/strong>/, /<em> italic<\/em>/, /href="https:\/\/example.com\/"/, /<ol/, /<ul/, /data:image\/png/]) assert.match(html, pattern);
  await screenshot(owner, 'docx-editor');
  await owner.evaluate("Object.defineProperty(document.querySelector('#docx-input'), 'files', {value:[new File(['broken'],'bad.docx')],configurable:true}); document.querySelector('#docx-input').onchange()");
  await owner.wait("!document.querySelector('#import-docx').disabled");
  assert.match(await owner.evaluate("document.querySelector('#notice').textContent"), /current document was kept/);
  assert.deepEqual(await owner.evaluate(`${editor}.getJSON()`), content);
  await owner.evaluate(`(async()=>{
    Object.defineProperty(document.querySelector('#docx-input'),'files',{value:[new File([Uint8Array.from(atob(${JSON.stringify(encoded)}), c=>c.charCodeAt(0))],'slow.docx')],configurable:true});
    const importing=document.querySelector('#docx-input').onchange();
    ${editor}.commands.insertContentAt(${editor}.state.doc.content.size,'<p>Typed during import</p>');
    await importing;
  })()`);
  assert.match(await owner.evaluate("document.querySelector('#notice').textContent"), /changed during import/);
  assert.match(await owner.evaluate(`${editor}.getText()`), /Typed during import/);
  await owner.evaluate(`${editor}.commands.setContent(${JSON.stringify(content)})`);
  // Capture the real browser export, then feed it to the real worker importer.
  await owner.evaluate(`window.originalCreateURL=URL.createObjectURL; URL.createObjectURL=blob=>{window.exportedDocx=blob; return window.originalCreateURL(blob)}; window.originalAnchorClick=HTMLAnchorElement.prototype.click; HTMLAnchorElement.prototype.click=function(){window.exportedName=this.download}; document.querySelector('#export').click()`);
  await owner.wait("!document.querySelector('#export').disabled");
  assert.equal(await owner.evaluate('window.exportedName'), 'Rich team report.docx');
  assert.ok(await owner.evaluate('window.exportedDocx.size > 1000'));
  await owner.evaluate(`(async()=>{URL.createObjectURL=window.originalCreateURL; HTMLAnchorElement.prototype.click=window.originalAnchorClick; Object.defineProperty(document.querySelector('#docx-input'),'files',{value:[new File([window.exportedDocx],'roundtrip.docx')],configurable:true}); await document.querySelector('#docx-input').onchange()})()`);
  assert.match(await owner.evaluate("document.querySelector('#notice').textContent"), /Imported DOCX/);
  assert.match(await owner.evaluate(`${editor}.getHTML()`), /<strong>Bold<\/strong>/);
  await owner.evaluate(`${editor}.commands.setTextSelection({from:1,to:5}); document.querySelector('[data-rich="bold"]').click()`);
  assert.match(await owner.evaluate(`${editor}.getHTML()`), /<strong>Team<\/strong>/);
  await owner.evaluate("document.querySelector('#share').click()");
  await owner.wait("document.querySelector('#share-dialog').open");
  const code = await owner.evaluate("document.querySelector('#invite-code').value");
  await owner.evaluate("document.querySelector('#share-dialog').close()");
  const guest = await page(`${base}/${code}`);
  await guest.wait("document.body.classList.contains('docx-document') && document.querySelector('#rich-editor').textContent.includes('Team report')");
  assert.equal(await guest.evaluate("document.querySelector('#preview').hidden"), true);
  await cdp('Network.enable', {}, guest.sessionId);
  await cdp('Network.emulateNetworkConditions', { offline: true, latency: 0, downloadThroughput: 0, uploadThroughput: 0 }, guest.sessionId);
  await guest.evaluate(`${editor}.commands.insertContentAt(${editor}.state.doc.content.size, {type:'paragraph',content:[{type:'text',text:'Offline collaborator',marks:[{type:'italic'}]}]})`);
  await owner.evaluate(`${editor}.commands.insertContentAt(${editor}.state.doc.content.size, {type:'paragraph',content:[{type:'text',text:'Online author',marks:[{type:'bold'}]}]})`);
  await owner.evaluate(`(async()=>{document.querySelector('#upload-photo').click(); const bytes=Uint8Array.from(atob(${JSON.stringify(PNG.split(',')[1])}), c=>c.charCodeAt(0)); Object.defineProperty(document.querySelector('#photo-input'),'files',{value:[new File([bytes],'added.png',{type:'image/png'})],configurable:true}); await document.querySelector('#photo-input').onchange()})()`);
  assert.match(await owner.evaluate("document.querySelector('#notice').textContent"), /Photo added/);
  await cdp('Network.emulateNetworkConditions', { offline: false, latency: 0, downloadThroughput: -1, uploadThroughput: -1 }, guest.sessionId);
  await guest.evaluate("window.dispatchEvent(new Event('online'))");
  await owner.wait("document.querySelector('#rich-editor').textContent.includes('Offline collaborator')");
  await guest.wait("document.querySelector('#rich-editor').textContent.includes('Online author') && document.querySelectorAll('#rich-editor img[src]').length===2");
  assert.deepEqual(await owner.evaluate(`${editor}.getJSON()`), await guest.evaluate(`${editor}.getJSON()`));
  await owner.evaluate(`${editor}.commands.insertContentAt(${editor}.state.doc.content.size, '<p>Undo this sentence</p>'); document.querySelector('#undo').click()`);
  assert.equal(await owner.evaluate(`${editor}.getText().includes('Undo this sentence')`), false);
  assert.match(await owner.evaluate(`${editor}.getText()`), /Offline collaborator/);
  await owner.evaluate(`window.savedSetItem=Storage.prototype.setItem; Storage.prototype.setItem=function(key,value){if(key==='docdoc.documents.v1') throw new Error('Storage full'); return window.savedSetItem.call(this,key,value)}; ${editor}.commands.insertContentAt(${editor}.state.doc.content.size,'<p>Retained on save failure</p>')`);
  assert.match(await owner.evaluate("document.querySelector('#save-status').textContent"), /failed/);
  assert.match(await owner.evaluate(`${editor}.getText()`), /Retained on save failure/);
  await owner.evaluate("Storage.prototype.setItem=window.savedSetItem; document.querySelector('#title').dispatchEvent(new Event('input'))");
  assert.match(await owner.evaluate("document.querySelector('#save-status').textContent"), /Saved/);
  await guest.evaluate("navigator.serviceWorker.ready");
  await guest.wait('!!navigator.serviceWorker.controller');
  const cached = await guest.evaluate("caches.keys().then(keys=>caches.open(keys[0])).then(cache=>cache.keys()).then(keys=>keys.map(request=>new URL(request.url).pathname))");
  assert.ok(cached.includes('/assets/docx-worker.js')); assert.ok(cached.includes('/assets/app.js'));
  await cdp('Network.emulateNetworkConditions', { offline: true, latency: 0, downloadThroughput: 0, uploadThroughput: 0 }, guest.sessionId);
  await cdp('Page.reload', {}, guest.sessionId);
  await guest.wait("document.querySelector('#rich-editor')?.textContent.includes('Offline collaborator')");
  await guest.evaluate(`${editor}.commands.insertContentAt(${editor}.state.doc.content.size, '<p>Offline after reload</p>')`);
  assert.match(await guest.evaluate("document.querySelector('#save-status').textContent"), /Saved/);
  // The conversion worker and export libraries are usable after an offline reload.
  await guest.evaluate(`Object.defineProperty(document.querySelector('#docx-input'),'files',{value:[new File([Uint8Array.from(atob(${JSON.stringify(encoded)}), c=>c.charCodeAt(0))],'offline.docx')],configurable:true}); document.querySelector('#docx-input').onchange()`);
  await guest.wait("!document.querySelector('#import-docx').disabled");
  assert.match(await guest.evaluate("document.querySelector('#notice').textContent"), /Imported DOCX/);
  await guest.evaluate("[...document.querySelectorAll('#documents button')].find(button=>button.textContent==='A fresh start').click()");
  assert.equal(await guest.evaluate("document.body.classList.contains('docx-document')"), false);
  await guest.evaluate("[...document.querySelectorAll('#documents button')].find(button=>button.textContent==='Rich team report').click()");
  assert.equal(await guest.evaluate("document.body.classList.contains('docx-document')"), true);
  await cdp('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true }, owner.sessionId);
  assert.equal(await owner.evaluate("document.documentElement.scrollWidth <= window.innerWidth"), true);
  await screenshot(owner, 'docx-mobile');
  // Legacy local records open as Markdown without a type prompt.
  const legacy = await page();
  await legacy.evaluate(`const records=${saved}; delete records[0].kind; localStorage.setItem('docdoc.documents.v1',JSON.stringify(records))`);
  await cdp('Page.reload', {}, legacy.sessionId);
  await legacy.wait("document.querySelector('#editor')?.value.includes('A fresh start')");
  assert.equal(await legacy.evaluate("document.querySelector('#new-dialog').open"), false);
  console.log('DOCX browser checks passed: creation/defaults, import/export and images, failed-import preservation, concurrent rich edits, reconnect, offline reload/conversion, document switching, legacy records, mobile.');
}
